import Head from "next/head";
import Image from "next/legacy/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Aboutus from "@/components/Aboutus";
import Header from "@/components/Header";

import { Component } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NTC Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ntc2.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
    
        <div>
          <Aboutus />
        </div>
      </main>
    </>
  );
}
